# Generated by Django 3.2.16 on 2023-12-29 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20231229_1645'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'default_related_name': 'posts', 'ordering': ('pub_date',)},
        ),
    ]
